/**
 * GENERATED by `pnpm audio:sfx -- --ship` (tools/audio/build-sfx.mjs) — do not
 * edit by hand; change the cue sheet (tools/audio/sfx/recipes.mjs) and rebuild.
 *
 * Which sprite file each rendered cue lives in, where its takes sit in it
 * (seconds), how the runtime picks a take, and the gain that puts it at its
 * target level in the mix (before the player's slider). Tier 1 is what the
 * first level needs; tier 2 loads after it.
 */
import type { SfxCueSpec, SfxSpriteSpec } from '@/game/audio/sfxPick'

export const SFX_SPRITES: Readonly<Record<string, SfxSpriteSpec>> = {
  foot: {
    file: 'sfx-foot',
    tier: 1,
    seconds: 3.748,
    bytes: 15874
  },
  chain: {
    file: 'sfx-chain',
    tier: 1,
    seconds: 10.845,
    bytes: 27916
  },
  flow: {
    file: 'sfx-flow',
    tier: 1,
    seconds: 9.105,
    bytes: 38868
  },
  props: {
    file: 'sfx-props',
    tier: 2,
    seconds: 6.454,
    bytes: 32860
  },
  sets: {
    file: 'sfx-sets',
    tier: 2,
    seconds: 14.82,
    bytes: 58465
  },
  boss: {
    file: 'sfx-boss',
    tier: 2,
    seconds: 5.911,
    bytes: 25058
  }
}

export const SFX_CUES: Readonly<Record<string, SfxCueSpec>> = {
  stompLight: {
    sprite: 'foot',
    gain: 0.15551,
    pick: 'rotate',
    slots: [
      [
        0.06,
        0.07569
      ],
      [
        0.19569,
        0.07764
      ],
      [
        0.33333,
        0.07234
      ],
      [
        0.46567,
        0.07361
      ],
      [
        0.59927,
        0.07537
      ]
    ],
    rate: 0.03
  },
  stompHeavy: {
    sprite: 'foot',
    gain: 0.36979,
    pick: 'rotate',
    slots: [
      [
        0.73465,
        0.36567
      ],
      [
        1.16032,
        0.34803
      ],
      [
        1.56834,
        0.34753
      ]
    ],
    rate: 0.025,
    ratePower: [
      1.03,
      0.97
    ],
    gainPower: [
      0.8,
      1
    ]
  },
  land: {
    sprite: 'foot',
    gain: 0.27129,
    pick: 'rotate',
    slots: [
      [
        1.97587,
        0.26023
      ],
      [
        2.2961,
        0.26023
      ]
    ],
    rate: 0.03
  },
  charge: {
    sprite: 'foot',
    gain: 0.09612,
    pick: 'loop',
    slots: [
      [
        2.61633,
        0.80005
      ]
    ],
    loop: [
      2.76635,
      3.26635
    ]
  },
  chargeReady: {
    sprite: 'foot',
    gain: 0.23356,
    pick: 'rotate',
    slots: [
      [
        3.47637,
        0.21138
      ]
    ]
  },
  chainStep: {
    sprite: 'chain',
    gain: 0.61136,
    pick: 'index',
    slots: [
      [
        0.06,
        0.55002
      ],
      [
        0.67002,
        0.55002
      ],
      [
        1.28005,
        0.55002
      ],
      [
        1.89007,
        0.55002
      ],
      [
        2.50009,
        0.55002
      ],
      [
        3.11011,
        0.55002
      ],
      [
        3.72014,
        0.55002
      ],
      [
        4.33016,
        0.55002
      ],
      [
        4.94018,
        0.55002
      ],
      [
        5.5502,
        0.48971
      ],
      [
        6.09991,
        0.41488
      ],
      [
        6.57478,
        0.31102
      ],
      [
        6.9458,
        0.38127
      ],
      [
        7.38707,
        0.37324
      ],
      [
        7.82032,
        0.38177
      ]
    ]
  },
  chainBreak: {
    sprite: 'chain',
    gain: 0.1159,
    pick: 'rotate',
    slots: [
      [
        8.26209,
        0.42476
      ],
      [
        8.74685,
        0.48726
      ]
    ]
  },
  grow: {
    sprite: 'chain',
    gain: 0.07287,
    pick: 'rotate',
    slots: [
      [
        9.2941,
        0.16853
      ],
      [
        9.52263,
        0.16821
      ],
      [
        9.75084,
        0.16834
      ],
      [
        9.97918,
        0.16839
      ]
    ],
    rate: 0.02,
    ratePower: [
      0.94,
      1.18
    ]
  },
  deflate: {
    sprite: 'chain',
    gain: 0.0966,
    pick: 'rotate',
    slots: [
      [
        10.20757,
        0.57782
      ]
    ],
    rate: 0.03
  },
  feverReady: {
    sprite: 'flow',
    gain: 0.17255,
    pick: 'rotate',
    slots: [
      [
        0.06,
        0.99002
      ]
    ]
  },
  feverStart: {
    sprite: 'flow',
    gain: 0.25725,
    pick: 'rotate',
    slots: [
      [
        1.11002,
        1.64299
      ]
    ]
  },
  feverEnd: {
    sprite: 'flow',
    gain: 0.12149,
    pick: 'rotate',
    slots: [
      [
        2.81302,
        0.48195
      ]
    ]
  },
  finisher: {
    sprite: 'flow',
    gain: 0.37885,
    pick: 'index',
    slots: [
      [
        3.35497,
        0.99315
      ],
      [
        4.40812,
        1.28086
      ]
    ]
  },
  heartbeat: {
    sprite: 'flow',
    gain: 0.27644,
    pick: 'rotate',
    slots: [
      [
        5.74898,
        0.30726
      ],
      [
        6.11624,
        0.32077
      ]
    ],
    rate: 0.015
  },
  star: {
    sprite: 'flow',
    gain: 0.25425,
    pick: 'index',
    slots: [
      [
        6.49701,
        0.62336
      ],
      [
        7.18036,
        0.76599
      ],
      [
        8.00635,
        0.8
      ]
    ]
  },
  tick: {
    sprite: 'flow',
    gain: 0.16065,
    pick: 'alternate',
    slots: [
      [
        8.86635,
        0.059
      ],
      [
        8.98535,
        0.05959
      ]
    ],
    rate: 0.01
  },
  pivot: {
    sprite: 'props',
    gain: 0.10971,
    pick: 'rotate',
    slots: [
      [
        0.06,
        0.27401
      ],
      [
        0.39401,
        0.2741
      ]
    ],
    rate: 0.03
  },
  slide: {
    sprite: 'props',
    gain: 0.0752,
    pick: 'loop',
    slots: [
      [
        0.72812,
        0.80005
      ]
    ],
    loop: [
      0.87814,
      1.37814
    ]
  },
  spike: {
    sprite: 'props',
    gain: 0.22808,
    pick: 'rotate',
    slots: [
      [
        1.58816,
        0.49859
      ],
      [
        2.14676,
        0.50127
      ]
    ],
    rate: 0.02
  },
  salt: {
    sprite: 'props',
    gain: 0.2041,
    pick: 'rotate',
    slots: [
      [
        2.70803,
        0.51256
      ],
      [
        3.28059,
        0.51197
      ]
    ],
    rate: 0.03
  },
  magnet: {
    sprite: 'props',
    gain: 0.24066,
    pick: 'rotate',
    slots: [
      [
        3.85256,
        0.57841
      ]
    ]
  },
  sweep: {
    sprite: 'props',
    gain: 0.10726,
    pick: 'rotate',
    slots: [
      [
        4.49098,
        0.19465
      ],
      [
        4.74562,
        0.19465
      ],
      [
        5.00027,
        0.19469
      ]
    ],
    rate: 0.03
  },
  podHatch: {
    sprite: 'props',
    gain: 0.06573,
    pick: 'rotate',
    slots: [
      [
        5.25497,
        0.52494
      ]
    ]
  },
  arc: {
    sprite: 'props',
    gain: 0.28168,
    pick: 'rotate',
    slots: [
      [
        5.83991,
        0.12626
      ],
      [
        6.02617,
        0.07878
      ],
      [
        6.16494,
        0.08721
      ],
      [
        6.31215,
        0.08141
      ]
    ],
    rate: 0.04
  },
  rushTell: {
    sprite: 'sets',
    gain: 0.16452,
    pick: 'rotate',
    slots: [
      [
        0.06,
        1.3
      ]
    ]
  },
  rushGo: {
    sprite: 'sets',
    gain: 0.07829,
    pick: 'rotate',
    slots: [
      [
        1.42,
        0.31488
      ]
    ]
  },
  multi: {
    sprite: 'sets',
    gain: 0.12308,
    pick: 'stack',
    slots: [
      [
        1.79488,
        0.33927
      ],
      [
        2.19415,
        0.34177
      ],
      [
        2.59592,
        0.33791
      ],
      [
        2.99383,
        0.33252
      ],
      [
        3.38635,
        0.31111
      ],
      [
        3.75746,
        0.26508
      ]
    ]
  },
  flip: {
    sprite: 'sets',
    gain: 0.21791,
    pick: 'rotate',
    slots: [
      [
        4.08254,
        0.38662
      ],
      [
        4.52916,
        0.39497
      ]
    ],
    rate: 0.03
  },
  kick: {
    sprite: 'sets',
    gain: 0.2497,
    pick: 'rotate',
    slots: [
      [
        4.98413,
        0.33351
      ],
      [
        5.37764,
        0.33361
      ],
      [
        5.77125,
        0.33361
      ]
    ],
    rate: 0.03
  },
  pins: {
    sprite: 'sets',
    gain: 0.40492,
    pick: 'index',
    slots: [
      [
        6.16485,
        1.09365
      ],
      [
        7.3185,
        1.35687
      ]
    ]
  },
  boxDrop: {
    sprite: 'sets',
    gain: 0.25939,
    pick: 'rotate',
    slots: [
      [
        8.73537,
        0.34127
      ]
    ]
  },
  boxHit: {
    sprite: 'sets',
    gain: 0.45026,
    pick: 'index',
    slots: [
      [
        9.13664,
        0.08535
      ],
      [
        9.282,
        0.07819
      ],
      [
        9.42018,
        0.07379
      ]
    ],
    indexScale: 3,
    indexBase: -1
  },
  boxOpen: {
    sprite: 'sets',
    gain: 0.34089,
    pick: 'rotate',
    slots: [
      [
        9.55397,
        0.74608
      ]
    ]
  },
  trialEnd: {
    sprite: 'sets',
    gain: 0.16479,
    pick: 'rotate',
    slots: [
      [
        10.36005,
        0.48567
      ]
    ]
  },
  quake: {
    sprite: 'sets',
    gain: 0.49853,
    pick: 'rotate',
    slots: [
      [
        10.90571,
        0.75138
      ]
    ]
  },
  echo: {
    sprite: 'sets',
    gain: 0.30299,
    pick: 'rotate',
    slots: [
      [
        11.7171,
        0.30032
      ]
    ]
  },
  twistTell: {
    sprite: 'sets',
    gain: 0.11347,
    pick: 'rotate',
    slots: [
      [
        12.07741,
        0.87252
      ]
    ]
  },
  party: {
    sprite: 'sets',
    gain: 0.28883,
    pick: 'rotate',
    slots: [
      [
        13.00993,
        1.75002
      ]
    ]
  },
  bossPhase: {
    sprite: 'boss',
    gain: 0.20844,
    pick: 'rotate',
    slots: [
      [
        0.06,
        1.2
      ]
    ]
  },
  bossCharge: {
    sprite: 'boss',
    gain: 0.20099,
    pick: 'rotate',
    slots: [
      [
        1.32,
        0.64862
      ]
    ]
  },
  bossBeam: {
    sprite: 'boss',
    gain: 0.13649,
    pick: 'rotate',
    slots: [
      [
        2.02862,
        2.56281
      ]
    ]
  },
  bossCounter: {
    sprite: 'boss',
    gain: 0.26214,
    pick: 'rotate',
    slots: [
      [
        4.65143,
        1.2
      ]
    ]
  }
}
